name: espaloma
channels:
  - openeye
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - ambertools=22.0=py39h59419a8_3
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha30fb19_3
  - arpack=3.7.0=hefb7bc6_2
  - arrow-cpp=10.0.1=h88f4db0_3_cpu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-auth=0.6.21=h79862ba_1
  - aws-c-cal=0.5.20=hdc31e88_3
  - aws-c-common=0.8.5=hb7f2c08_0
  - aws-c-compression=0.2.16=hfb1f584_0
  - aws-c-event-stream=0.2.16=hb9fe1ad_0
  - aws-c-http=0.6.29=h40fbe91_0
  - aws-c-io=0.13.11=hb3bb6ef_2
  - aws-c-mqtt=0.7.13=h9baa75a_10
  - aws-c-s3=0.2.1=hfb6aee5_2
  - aws-c-sdkutils=0.1.7=hfb1f584_0
  - aws-checksums=0.1.14=hfb1f584_0
  - aws-crt-cpp=0.18.16=hb25e9ed_5
  - aws-sdk-cpp=1.9.379=h8c00297_6
  - babel=2.11.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - blosc=1.21.2=hebb52c4_0
  - boltons=21.0.0=pyhd8ed1ab_0
  - boost=1.74.0=py39ha1f3e3e_5
  - boost-cpp=1.74.0=h8b082ac_8
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py39ha30fb19_1005
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.12.7=h033912b_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h904041c_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h131948b_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - clang=14.0.6=h694c41f_0
  - clang-14=14.0.6=default_h55ffa42_0
  - clangxx=14.0.6=default_h55ffa42_0
  - codecov=2.1.12=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.6=py39h92daf61_0
  - coverage=7.0.5=py39ha30fb19_0
  - cryptography=39.0.0=py39hbeae22c_0
  - curl=7.86.0=h581aaea_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.33=py39h7a8716b_0
  - debugpy=1.6.5=py39h7a8716b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dgl=0.9.1=py39_0
  - docutils=0.19=py39h6e9494a_1
  - ele=0.2.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_0
  - fftw=3.3.10=nompi_h4fa670e_106
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39ha30fb19_1
  - forcefield-utilities=0.2.1=pyhd8ed1ab_0
  - foyer=0.11.3=pyhd8ed1ab_0
  - freetype=2.12.1=h3f81eb7_1
  - gettext=0.21.1=h8a4c099_0
  - gflags=2.2.2=hb1e8313_1004
  - glib=2.74.1=hbc0c0cd_1
  - glib-tools=2.74.1=hbc0c0cd_1
  - glog=0.6.0=h8ac2a54_0
  - gmp=6.2.1=h2e338ed_0
  - gmpy2=2.1.2=py39h2da61ea_1
  - gmso=0.9.1=pyhd8ed1ab_0
  - greenlet=2.0.1=py39h7a8716b_0
  - gsd=2.7.0=py39h7cc1f47_1
  - gst-plugins-base=1.21.3=h37e1711_1
  - gstreamer=1.21.3=h1d18e73_1
  - h5py=3.7.0=nompi_py39h7d40783_102
  - hdf4=4.2.15=h7aa5921_5
  - hdf5=1.12.2=nompi_h1f71328_100
  - hoomd=3.8.0=cpu_py39h5e8e8a3_0
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.20.1=pyh736e0ef_0
  - ipython=8.8.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.2=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hac89ed1_2
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py39h6e9494a_8
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=5.1.3=py39h6e9494a_0
  - jupyter_events=0.6.2=pyhd8ed1ab_0
  - jupyter_server=2.0.6=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2022.09.30=hb7f2c08_2
  - kiwisolver=1.4.4=py39h92daf61_1
  - krb5=1.19.3=hb98e516_0
  - lark-parser=0.12.0=pyhd8ed1ab_0
  - lcms2=2.14=h29502cd_1
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20220623.0=cxx17_h844d122_6
  - libarrow=10.0.1=h6707bc3_3_cpu
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libclang=15.0.6=default_h20dc2f0_0
  - libclang-cpp=14.0.6=default_h55ffa42_0
  - libclang-cpp14=14.0.6=default_h55ffa42_0
  - libclang13=15.0.6=default_hc4b5f92_0
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=7.86.0=h581aaea_1
  - libcxx=14.0.6=hccf4f1f_0
  - libdeflate=1.14=hb7f2c08_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.10=h7d65743_4
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=11_3_0_h97931a8_27
  - libgfortran5=11.3.0=h082f757_27
  - libglib=2.74.1=h4c723e1_1
  - libgoogle-cloud=2.5.0=hb5e37a9_1
  - libgrpc=1.51.1=h966d1d5_0
  - libiconv=1.17=hac89ed1_0
  - libidn2=2.3.4=hb7f2c08_0
  - libjpeg-turbo=2.1.4=hb7f2c08_0
  - liblapack=3.9.0=16_osx64_openblas
  - libllvm14=14.0.6=h5b596cc_1
  - libllvm15=15.0.6=h7001e86_0
  - libnetcdf=4.8.1=nompi_hc61b76e_106
  - libnghttp2=1.51.0=he2ab024_0
  - libogg=1.3.4=h35c211d_1
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.39=ha978bb4_0
  - libpq=15.1=hb1ae2b1_1
  - libprotobuf=3.21.12=hbc0c0cd_0
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.40.0=ha978bb4_0
  - libssh2=1.10.0=h47af595_3
  - libthrift=0.16.0=h16802d8_2
  - libtiff=4.5.0=h6268bbc_0
  - libunistring=0.9.10=h0d85af4_0
  - libutf8proc=2.8.0=hb7f2c08_0
  - libvorbis=1.3.7=h046ec9c_0
  - libwebp-base=1.2.4=h775f41a_0
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.10.3=hb9e07b5_0
  - libxslt=1.1.37=h5d22bc9_0
  - libzip=1.9.2=h6db710c_1
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=15.0.6=h61d9ccf_0
  - lxml=4.9.2=py39hfbce9ca_0
  - lz4-c=1.9.3=he49afe7_1
  - markupsafe=2.1.1=py39ha30fb19_2
  - matplotlib=3.6.2=py39h6e9494a_0
  - matplotlib-base=3.6.2=py39hb2f573b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mbuild=0.15.1=pyhd8ed1ab_0
  - mdtraj=1.9.7=py39h5456c6e_4
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2022.2.1=h44ed08c_16952
  - mpc=1.2.1=hbb51d92_0
  - mpfr=4.1.0=h0f52abe_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py39h92daf61_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.31=hc4b2c72_0
  - mysql-libs=8.0.31=h8658499_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.7=pyhd8ed1ab_0
  - nbconvert-core=7.2.7=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.7=pyhd8ed1ab_0
  - nbformat=5.7.1=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf-fortran=4.6.0=nompi_h96bf37d_101
  - networkx=3.0=pyhd8ed1ab_0
  - nglview=3.0.3=pyh8a188c0_0
  - ninja=1.11.0=h1b54a9f_0
  - nose=1.3.7=py_1006
  - nose-timer=1.0.1=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.78=ha8197d3_0
  - numexpr=2.8.3=py39hecff1ad_1
  - numpy=1.24.1=py39hdfa1d0c_0
  - ocl_icd_wrapper_apple=1.0.0=hbcb3906_0
  - openeye-toolkits=2022.2.1=py39_0
  - openff-forcefields=2.0.0=pyh6c4a22f_0
  - openff-toolkit=0.10.6=pyhd8ed1ab_0
  - openff-toolkit-base=0.10.6=pyhd8ed1ab_0
  - openff-units=0.2.0=pyh1a96a4e_0
  - openff-utilities=0.1.7=pyh1a96a4e_0
  - openjpeg=2.5.0=h13ac156_2
  - openmm=7.7.0=py39h8d72adf_0_khronos
  - openmmforcefields=0.11.2=pyhd8ed1ab_1
  - openssl=3.0.7=hfd90126_1
  - orc=1.8.1=ha9d861c_0
  - packaging=23.0=pyhd8ed1ab_0
  - packmol=20.010=h508aa58_0
  - pandas=1.5.2=py39hecff1ad_2
  - pandoc=2.19.2=h694c41f_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parmed=3.4.3=py39h7a8716b_3
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - perl=5.32.1=2_h0d85af4_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h193cfb4_0
  - pint=0.20.1=pyhd8ed1ab_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - plotly=5.11.0=pyhd8ed1ab_1
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - pooch=1.6.0=pyhd8ed1ab_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - protobuf=4.21.12=py39h7a8716b_0
  - psutil=5.9.4=py39ha30fb19_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py3dmol=2.0.0.post2=pyhd8ed1ab_0
  - pyarrow=10.0.1=py39h2db5b05_3_cpu
  - pybind11-abi=4=hd8ed1ab_3
  - pycairo=1.23.0=py39h41776c8_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.4=py39ha30fb19_1
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h327fbb6_2
  - pyqt5-sip=12.11.0=py39hc100f75_2
  - pyrsistent=0.19.3=py39ha30fb19_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.7.0=py39hc15ac9a_3
  - pytest=7.2.0=pyhd8ed1ab_2
  - pytest-cov=4.0.0=pyhd8ed1ab_0
  - python=3.9.15=h709bd14_0_cpython
  - python-constraint=1.4.0=py_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytorch=1.13.0=cpu_py39h0a103a1_0
  - pytz=2022.7=pyhd8ed1ab_0
  - pyyaml=6.0=py39ha30fb19_5
  - pyzmq=24.0.1=py39hed8f129_1
  - qcelemental=0.25.1=pyhd8ed1ab_1
  - qcportal=0.15.8=pyhd8ed1ab_0
  - qt-main=5.15.6=h0916ed4_4
  - qtconsole=5.4.0=pyhd8ed1ab_0
  - qtconsole-base=5.4.0=pyha770c72_0
  - qtpy=2.3.0=pyhd8ed1ab_0
  - rdkit=2022.09.1=py39h67dd817_0
  - re2=2022.06.01=hb486fe8_1
  - readline=8.1.2=h3899abd_0
  - reportlab=3.6.12=py39h4e200fb_2
  - requests=2.28.1=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - scipy=1.10.0=py39h8a15683_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - sip=6.7.5=py39h7a8716b_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h6db0672_2
  - smirnoff99frosst=1.1.0=pyh44b312d_0
  - snappy=1.1.9=h225ccf5_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=6.1.3=pyhd8ed1ab_0
  - sphinx_rtd_theme=0.5.2=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlalchemy=1.4.46=py39ha30fb19_0
  - sqlite=3.40.0=h9ae0607_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py39h6e9494a_2
  - tbb=2021.7.0=hb8565cd_1
  - tenacity=8.1.0=pyhd8ed1ab_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tinydb=4.7.0=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py39ha30fb19_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.8.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py39ha30fb19_0
  - unyt=2.9.3=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - validators=0.18.2=pyhd3deb0d_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h35c211d_1002
  - xorg-libice=1.0.10=h0d85af4_0
  - xorg-libsm=1.2.3=h0d85af4_1000
  - xorg-libx11=1.7.2=h0d85af4_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xorg-libxext=1.3.4=h0d85af4_1
  - xorg-libxt=1.2.1=h0d85af4_2
  - xorg-xextproto=7.3.0=h35c211d_1002
  - xorg-xproto=7.0.31=h35c211d_1007
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hfa58983_4
  - pip:
      - amberlite==22.0
      - amberutils==21.0
      - espaloma==0.2.4+6.ga178702
      - mmpbsa-py==16.0
      - packmol-memgen==1.2.3rc0
      - pdb4amber==22.0
      - pytraj==2.0.6
      - sander==22.0
      - wget==3.2
prefix: /Users/madilyn/miniconda3/envs/espaloma
